name: run-python-linting

on: pull_request

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "."
            version: "~=24.4.0"
  
  # lint-dbt:
  #   uses: ./.github/workflows/sqlfluff.yaml
